root: true
parser: babel-eslint
extends:
  - airbnb
  - prettier
plugins:
  - prettier

rules:
  ###########
  # PLUGINS #
  ###########
  import/prefer-default-export: 0
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
  react/jsx-indent: 0
  react/no-unescaped-entities: 0

  ###########
  # BUILTIN #
  ###########
  no-param-reassign: 0
  no-underscore-dangle: 0
  no-plusplus: 0

  ###########
  # SPECIAL #
  ###########
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: false
